#!/bin/bash
 
NAME="sovazlutice.eu"                                  # Name of the application
DJANGODIR=/var/www/sovazlutice/production/django/             # Django project directory
SOCKFILE=/var/www/sovazlutice/run/gunicorn.sock  # we will communicte using this unix socket
USER=nginx                                        # the user to run as
GROUP=webdata                                     # the group to run as
NUM_WORKERS=1                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=sov.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=sov.wsgi                     # WSGI module name
TIMEOUT=300
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source /var/www/sovazlutice/production/virtenv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /var/www/sovazlutice/production/virtenv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --log-level=warning \
  --user $USER \
  --bind=unix:$SOCKFILE \
  --timeout $TIMEOUT

