#!/bin/bash
 
NAME="sovazlutice.eu"                                  # Name of the application
TIMEOUT=300
 
cd django
echo "Starting $NAME as `whoami` in `pwd`"
 
exec gunicorn sov.wsgi \
  --bind 0.0.0.0:8000 \
  --name $NAME \
  --log-level=debug \
  --timeout $TIMEOUT

